dataloader:
  data_root: /mnt/data/objaverse
  num_worker: 8
  split_data_path: /home/ubuntu/Open-Category-Mesh-Prediction/dataset/train_seen_uid.json
  batch_size: 16
  train: True

dataloader_test:
  data_root: /mnt/data/objaverse
  num_worker: 8
  split_data_path: /home/ubuntu/Open-Category-Mesh-Prediction/dataset/test_seen_uid.json
  batch_size: 16
  train: False

backbone:
  type: resnet50
  pretrained: True

bilinear_interpolation:
  output_size: [24, 24]

roi_head:
  type: MeshRCNNROIHeads
  NUM_CLASSES: None
  ROI_VOXEL_HEAD:
    input_shape: [2048, 24, 24]
    CUBIFY_THRESH: 0.2
    voxel_loss_weight: 1.0
    NUM_CONV: 4
    CONV_DIM: 256
    VOXEL_SIZE: 48
    CLASS_AGNOSTIC: True

  ROI_MESH_HEAD:
    NAME: "MeshRCNNGraphConvHead"
    INPUT_CHANNELS: [256, 512, 1024, 2048]
    NUM_STAGES: 3
    NUM_RES_GRAPH_CONVS: 2
    GRAPH_CONV_DIM: 128
    GRAPH_CONV_INIT: "normal"
    GT_NUM_SAMPLES: 5000
    PRED_NUM_SAMPLES: 5000
    CHAMFER_LOSS_WEIGHT: 1.0
    NORMALS_LOSS_WEIGHT: 0.0
    EDGE_LOSS_WEIGHT: 0.2
    GT_COORD_THRESH: 5.0

training:
  num_epochs: 10000
  batch_size: 64
  lr: 0.0005

  checkpoint_path: ./checkpoints/baseline
  checkpoint_interval: 1000
  resume: True

  device: "cuda"